language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --prefer-source

before_script:
  - mysql -e 'create database IF NOT EXISTS foobartest;' -uroot

script:
  - vendor/bin/phpunit --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true
